services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data  

  backend:
    build: ./backend
    restart: always
    env_file: backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    env_file: frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:  